[package]
name = "edge-btf-module-wasm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ckks-engine = "4.0.0"
wasm-bindgen = "0.2.100"
wasm-bindgen-cli = "0.2.100"
wasm-pack = "0.13.1"
